# Generated by Django 6.0 on 2025-12-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiOtpTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctopupno', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_otp_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtopMaster',
            fields=[
                ('ctopupno', models.CharField(db_column='ctopupno', max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50, null=True)),
                ('dealertype', models.CharField(db_column='dealertype', max_length=50, null=True)),
                ('dealer_id', models.IntegerField(db_column='dealer_id', null=True)),
                ('dealercode', models.CharField(db_column='dealercode', max_length=50, null=True)),
                ('issuedate', models.DateTimeField(db_column='issuedate', null=True)),
                ('cityid', models.IntegerField(db_column='cityid', null=True)),
                ('ssa_code', models.CharField(db_column='ssa_code', max_length=50, null=True)),
                ('circle_code', models.IntegerField(db_column='circle_code', null=True)),
                ('csccode', models.CharField(db_column='csccode', max_length=50, null=True)),
                ('attached_to', models.CharField(db_column='attached_to', max_length=50, null=True)),
                ('active', models.CharField(db_column='active', max_length=1)),
                ('deact_date', models.DateTimeField(db_column='deact_date', null=True)),
                ('ssa_city', models.CharField(db_column='ssa_city', max_length=50, null=True)),
                ('ref_dealer_id', models.IntegerField(db_column='ref_dealer_id', null=True)),
                ('master_dealer_id', models.IntegerField(db_column='master_dealer_id', null=True)),
                ('functional', models.CharField(db_column='functional', max_length=1, null=True)),
                ('sms_act', models.CharField(db_column='sms_act', max_length=50, null=True)),
                ('parent_ctopno', models.CharField(db_column='parent_ctopno', max_length=15, null=True)),
                ('contact_number', models.CharField(db_column='contact_number', max_length=50, null=True)),
                ('second_name', models.CharField(db_column='second_name', max_length=30, null=True)),
                ('last_name', models.CharField(db_column='last_name', max_length=30, null=True)),
                ('dealer_address', models.CharField(db_column='dealer_address', max_length=255, null=True)),
                ('dealer_status', models.CharField(db_column='dealer_status', max_length=15, null=True)),
            ],
            options={
                'db_table': 'ctop_master',
                'ordering': ['ctopupno'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GsmChoice',
            fields=[
                ('gsmno', models.CharField(db_column='gsmno', max_length=10, primary_key=True, serialize=False)),
                ('pin', models.CharField(db_column='pin', max_length=10, null=True)),
                ('mobileno', models.CharField(db_column='mobileno', max_length=10, null=True)),
                ('status', models.IntegerField(db_column='status', null=True)),
                ('csccode', models.CharField(db_column='csccode', max_length=20, null=True)),
                ('ssa_code', models.CharField(db_column='ssa_code', max_length=20, null=True)),
                ('circle_code', models.IntegerField(db_column='circle_code', null=True)),
                ('trans_date', models.DateTimeField(db_column='trans_date', null=True)),
                ('data_entry_date', models.DateTimeField(db_column='data_entry_date', null=True)),
                ('remarks', models.CharField(db_column='remarks', max_length=30, null=True)),
                ('ipaddress', models.CharField(db_column='ipaddress', max_length=20, null=True)),
                ('user_agent', models.CharField(db_column='user_agent', max_length=300, null=True)),
            ],
            options={
                'db_table': 'gsm_choice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Simpostpaid',
            fields=[
                ('simno', models.CharField(db_column='simno', max_length=19, primary_key=True, serialize=False)),
                ('pukno1', models.CharField(db_column='pukno1', max_length=15, null=True)),
                ('pukno2', models.CharField(db_column='pukno2', max_length=15, null=True)),
                ('pin1', models.CharField(db_column='pin1', max_length=10, null=True)),
                ('pin2', models.CharField(db_column='pin2', max_length=10, null=True)),
                ('location', models.CharField(db_column='location', max_length=50, null=True)),
                ('status', models.IntegerField(db_column='status', null=True)),
                ('issuedate', models.DateTimeField(db_column='issuedate', null=True)),
                ('vendor_code', models.IntegerField(db_column='vendor_code', null=True)),
                ('circle_code', models.IntegerField(db_column='circle_code', null=True)),
                ('circle', models.CharField(db_column='circle', max_length=3, null=True)),
                ('product_code', models.IntegerField(db_column='product_code', null=True)),
                ('imsi', models.BigIntegerField(db_column='imsi', null=True)),
                ('plancode', models.IntegerField(db_column='plancode', null=True)),
                ('changed_date', models.DateTimeField(db_column='changed_date', null=True)),
            ],
            options={
                'db_table': 'simpostpaid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Simprepaid',
            fields=[
                ('simno', models.CharField(db_column='simno', max_length=20, primary_key=True, serialize=False)),
                ('pukno1', models.CharField(db_column='pukno1', max_length=15, null=True)),
                ('pukno2', models.CharField(db_column='pukno2', max_length=15, null=True)),
                ('pin1', models.CharField(db_column='pin1', max_length=15, null=True)),
                ('pin2', models.CharField(db_column='pin2', max_length=15, null=True)),
                ('location', models.CharField(db_column='location', max_length=50, null=True)),
                ('status', models.IntegerField(db_column='status', null=True)),
                ('issuedate', models.DateTimeField(db_column='issuedate', null=True)),
                ('vendor_code', models.IntegerField(db_column='vendor_code', null=True)),
                ('circle_code', models.IntegerField(db_column='circle_code', null=True)),
                ('circle', models.CharField(db_column='circle', max_length=3, null=True)),
                ('product_code', models.IntegerField(db_column='product_code', null=True)),
                ('imsi', models.BigIntegerField(db_column='imsi', null=True)),
                ('plan_code', models.IntegerField(db_column='plan_code', null=True)),
                ('changed_date', models.DateTimeField(db_column='changed_date', null=True)),
            ],
            options={
                'db_table': 'simprepaid',
                'managed': False,
            },
        ),
    ]
