"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os,environ
from datetime import timedelta

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, True)
)
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
CORE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
# Build paths inside the project like this: BASE_DIR / 'subdir'.



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$)5j1&3o6b223sboe@$gm5yj)w@5&8x_p@@rx*0i_v_nuk#hih"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['10.201.222.68','127.0.0.1','sm.bsnl.co.in']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    "apps.apis",
    'rest_framework_simplejwt',
    'drf_spectacular'
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "apps.apis.authentication.CtopJWTAuthentication",
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',  # Add this line
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Sanchaar Mitra API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SECURITY': [{
        'type': 'http',
        'scheme': 'bearer',
        'bearerFormat': 'JWT',
    }],
    'SERVERS': [
        {'url': 'https://sm.bsnl.co.in/cosapp', 'description': 'Production server'},
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': 'VS6m_t%UCCh;bmJn_}5D.q9]0k[(3&b/(?F%DaPnxBA27BJ3EyMkfQH?pH4&}K_K',  # Use same as SECRET_KEY or environment variable
}

TIME_ZONE = 'Asia/Kolkata'
USE_TZ = True

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# if os.environ.get('DB_ENGINE') and os.environ.get('DB_ENGINE') == "postgres":
#     DATABASES = { 
#       'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#             'NAME': os.getenv('DB_NAME', 'appseed_db'),
#             'USER': os.getenv('DB_USER', 'appseed_db_usr'),
#             'PASSWORD': os.getenv('DB_PASSWORD', 'pass'),
#             'HOST': os.getenv('DB_HOST', 'localhost'),
#             'PORT': os.getenv('DB_PORT', 5432),  # Default PostgreSQL port
#         }, 
#     }
# else:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.sqlite3',
#             'NAME': 'db.sqlite3',
#         }
#     }

DATABASES = {
    'default': {   # Django's internal DB (SQLite or Postgres)
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'django_db.sqlite3',
    },

    'legacy': {    # Your legacy Postgres DB
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'legacy_db'),
        'USER': os.getenv('DB_USER', 'legacy_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'legacy_pass'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),  # keep as string

                # 🔥 Django 5.1 Psycopg Connection Pool
        # 'OPTIONS': {
        #     'pool': {
        #         'min_size': 1,     # Minimum idle connections
        #         'max_size': 2,    # Maximum active connections
        #         'max_waiting': 20, # Max threads waiting for a connection
        #         'timeout': 30,     # Seconds to wait before raising error
        #     }
        # }
    },

    'read': {    # Your legacy Postgres DB
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME_READ', 'read_db'),
        'USER': os.getenv('DB_USER_READ', 'read_user'),
        'PASSWORD': os.getenv('DB_PASSWORD_READ', 'read_pass'),
        'HOST': os.getenv('DB_HOST_READ', 'localhost'),
        'PORT': os.getenv('DB_PORT_READ', '5433'),  # keep as string
    }
}

ORACLE_CONFIG = {
    'user': os.getenv('ORACLE_USER'),
    'password': os.getenv('ORACLE_PASSWORD'),
    'dsn': os.getenv('ORACLE_DSN'),
}
DATABASE_ROUTERS = ['core.db_router.LegacyRouter']
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AADHAAR_PEPPER = env("AADHAAR_PEPPER")
DEFAULT_FROM_EMAIL=env("DEFAULT_FROM_EMAIL")